import type { LucideIcon } from 'lucide-react'
import { Cable, Camera, Fan, Gauge, Hammer, Lightbulb, ShieldCheck, Sun, Wrench } from 'lucide-react'

export const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logo-rtfGjGa1Xx2Oy5nwzt2QnknpS22gAi.png'

export const heroSlides = [
  { image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=2200&q=85', eyebrow: 'POWERING PROGRESS', title: 'Engineering certainty into every connection.', text: 'Electrical systems designed, installed, and maintained for the places where performance matters.', },
  { image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=2200&q=85', eyebrow: 'BUILT FOR PERFORMANCE', title: 'Infrastructure that works as hard as you do.', text: 'From industrial facilities to commercial developments, we deliver dependable technical outcomes.', },
  { image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=2200&q=85', eyebrow: 'SMARTER ENERGY', title: 'Practical innovation. Measurable efficiency.', text: 'Modern solar, power, and automation solutions tailored to your operation.', },
  { image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=2200&q=85', eyebrow: 'TRUSTED DELIVERY', title: 'A technical partner for the long term.', text: 'Clear thinking, disciplined execution, and responsive maintenance after handover.', },
  { image: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=2200&q=85', eyebrow: 'STIMA TECHNICS', title: 'Make your next project work better.', text: 'Talk to Kenya’s dependable electrical contracting and engineering team.', },
]

export type Service = { slug: string; title: string; short: string; description: string; icon: LucideIcon; image: string; scope: string[]; capabilities: string[]; benefits: string[]; applications: string[]; industries: string[] }
const baseImage = 'https://images.unsplash.com/photo-'
export const services: Service[] = [
  { slug: 'electrical-wiring-installation', title: 'Electrical Wiring & Installation', short: 'Safe, compliant power distribution for new builds and renovations.', description: 'We engineer and install electrical systems that are safe, efficient, maintainable, and ready for the demands of modern buildings.', icon: Cable, image: baseImage+'1558008258-3256797b43f3?auto=format&fit=crop&w=1400&q=85', scope: ['LV power distribution', 'Lighting and small power', 'Containment and cable management', 'Testing and commissioning'], capabilities: ['Load assessment and design', 'Full installation supervision', 'As-built documentation', 'Compliance testing'], benefits: ['Reliable day-to-day operation', 'Reduced lifecycle risk', 'Clean, maintainable installations'], applications: ['New builds', 'Fit-outs', 'Upgrades and refurbishments'], industries: ['Commercial', 'Industrial', 'Institutional', 'Residential'] },
  { slug: 'hvac', title: 'HVAC', short: 'Efficient climate systems for healthy, productive environments.', description: 'Our HVAC team integrates thermal comfort, energy efficiency, and dependable controls into one coordinated installation.', icon: Fan, image: baseImage+'1509391366360-2e959784a276?auto=format&fit=crop&w=1400&q=85', scope: ['Air conditioning', 'Ventilation systems', 'Controls and BMS integration', 'Preventive maintenance'], capabilities: ['System sizing', 'Equipment installation', 'Balancing and commissioning', 'Planned service'], benefits: ['Comfortable spaces', 'Lower energy consumption', 'Better asset life'], applications: ['Offices', 'Retail', 'Healthcare', 'Hospitality'], industries: ['Commercial', 'Healthcare', 'Hospitality', 'Education'] },
  { slug: 'cctv-installation', title: 'CCTV Installation', short: 'Intelligent surveillance designed around your people and property.', description: 'We deliver clear, resilient security camera systems with thoughtful coverage, access, and recording strategies.', icon: Camera, image: baseImage+'1557597774-9d2739d6a957?auto=format&fit=crop&w=1400&q=85', scope: ['Site survey and coverage plan', 'IP camera installation', 'Recording and monitoring', 'Remote access setup'], capabilities: ['Risk-based camera positioning', 'Networked video systems', 'System handover and training', 'Maintenance support'], benefits: ['Stronger visibility', 'Deterrence and evidence', 'Scalable security'], applications: ['Perimeters', 'Entrances', 'Production floors', 'Parking areas'], industries: ['Commercial', 'Industrial', 'Residential', 'Institutional'] },
  { slug: 'lifts-escalators', title: 'Lifts & Escalators', short: 'Vertical transportation systems specified for safety and uptime.', description: 'We coordinate lift and escalator electrical works with the wider building services package for smooth delivery.', icon: Gauge, image: baseImage+'1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=85', scope: ['Power supplies', 'Control interfaces', 'Installation coordination', 'Testing and handover'], capabilities: ['Interface management', 'Site coordination', 'Safety documentation', 'Planned maintenance'], benefits: ['Safe movement', 'Reduced disruption', 'Coordinated delivery'], applications: ['High-rise buildings', 'Malls', 'Hospitals', 'Transit'], industries: ['Commercial', 'Healthcare', 'Hospitality', 'Institutional'] },
  { slug: 'solar-design-installation', title: 'Solar Design & Installation', short: 'Clean, practical energy systems with returns you can measure.', description: 'We make solar easier to adopt with right-sized systems, quality installation, and clear performance expectations.', icon: Sun, image: baseImage+'1508514177221-188b1a7a7c9e?auto=format&fit=crop&w=1400&q=85', scope: ['Site and energy assessment', 'PV system design', 'Mounting and inverter installation', 'Monitoring and maintenance'], capabilities: ['Yield modelling', 'Grid-tied and hybrid systems', 'Battery-ready architecture', 'Performance review'], benefits: ['Lower operating costs', 'Energy resilience', 'Reduced carbon impact'], applications: ['Rooftops', 'Campuses', 'Industrial sites', 'Homes'], industries: ['Commercial', 'Industrial', 'Residential', 'Education'] },
  { slug: 'generator-installation-maintenance', title: 'Generator Installation & Maintenance', short: 'Standby power that starts when your operation needs it.', description: 'From selection to commissioning, we create dependable backup power systems with disciplined maintenance plans.', icon: Wrench, image: baseImage+'1518770660439-4636190af475?auto=format&fit=crop&w=1400&q=85', scope: ['Generator sizing', 'Changeover systems', 'Fuel and exhaust coordination', 'Service contracts'], capabilities: ['Load analysis', 'ATS integration', 'Commissioning tests', 'Emergency response'], benefits: ['Business continuity', 'Predictable performance', 'Longer equipment life'], applications: ['Critical facilities', 'Factories', 'Retail', 'Offices'], industries: ['Healthcare', 'Industrial', 'Commercial', 'Institutional'] },
  { slug: 'electrical-maintenance', title: 'Electrical Maintenance', short: 'Proactive care that keeps your systems dependable.', description: 'Our maintenance programmes find small issues before they become costly outages or safety risks.', icon: Wrench, image: baseImage+'1581094794329-c8112a89af12?auto=format&fit=crop&w=1400&q=85', scope: ['Planned inspections', 'Fault finding', 'Thermal checks', 'Emergency call-outs'], capabilities: ['Asset registers', 'Condition reporting', 'Compliance checks', 'Response coordination'], benefits: ['Less downtime', 'Safer workplaces', 'Better maintenance visibility'], applications: ['Facilities', 'Plant rooms', 'Distribution boards'], industries: ['All sectors'] },
  { slug: 'electric-systems-alarms', title: 'Electric Systems & Alarms', short: 'Integrated detection and control for safer environments.', description: 'We install and maintain coordinated alarm and electrical systems that support fast, informed response.', icon: ShieldCheck, image: baseImage+'1558008258-3256797b43f3?auto=format&fit=crop&w=1400&q=85', scope: ['Fire alarms', 'Intrusion detection', 'Access control interfaces', 'Emergency systems'], capabilities: ['System design', 'Device installation', 'Testing and drills', 'User training'], benefits: ['Earlier warning', 'Clearer response', 'Integrated protection'], applications: ['Buildings', 'Sites', 'Warehouses'], industries: ['Commercial', 'Industrial', 'Institutional'] },
  { slug: 'electrical-supplies-installation', title: 'Electrical Supplies & Installation', short: 'Quality equipment, sourced responsibly and installed correctly.', description: 'We supply the components and technical expertise needed to complete electrical projects with confidence.', icon: Hammer, image: baseImage+'1586864387967-d02ef85d93e8?auto=format&fit=crop&w=1400&q=85', scope: ['Equipment sourcing', 'Distribution equipment', 'Lighting and controls', 'Installation support'], capabilities: ['Technical specification', 'Supplier coordination', 'Quality checks', 'Site delivery'], benefits: ['Fewer procurement gaps', 'Fit-for-purpose equipment', 'One accountable partner'], applications: ['Projects', 'Refurbishments', 'Maintenance works'], industries: ['Commercial', 'Industrial', 'Construction'] },
]
export const stats = [['12+', 'Years of experience'], ['180+', 'Clients supported'], ['420+', 'Projects delivered']]
export const markets = ['Construction', 'Commercial Buildings', 'Industrial Facilities', 'Schools & Educational Institutions', 'Residential Developments', 'Property & Facilities Management', 'Hospitality', 'Healthcare', 'Other Institutions']
export const nav = [{ label: 'Home', href: '/' }, { label: 'About Us', href: '/about', children: ['History', 'Mission & Vision', 'Company Principles', 'Core Values', 'Markets'] }, { label: 'Services', href: '/services' }, { label: 'Careers', href: '/careers' }, { label: 'Contact', href: '/contact' }]
export const testimonial = { quote: 'Stima Technics brought discipline, clarity, and real technical ownership to our project. Their team delivered exactly what was promised.', name: 'Project Director', company: 'Commercial Development Partner' }
export const testimonials = [
  {
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=85',
    quote: 'The team was responsive, disciplined, and careful with every detail from planning to handover.',
    name: 'John Mwangi',
    role: 'Director, Mwangaza Hospital',
  },
  {
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=85',
    quote: 'They made a complex electrical scope feel manageable and kept us informed at every step.',
    name: 'Amina Wanjiku',
    role: 'Facilities Manager, Greenfield School',
  },
  {
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=85',
    quote: 'We got practical advice, clean execution, and a result that has held up well in daily operations.',
    name: 'David Otieno',
    role: 'Operations Lead, Metro Logistics Ltd',
  },
]

export function getService(slug: string) { return services.find((service) => service.slug === slug) }
export function slugLabel(slug: string) { return slug.split('-').map((word) => word[0].toUpperCase()+word.slice(1)).join(' ') }

export const principles = [{ title: 'Safety before speed', text: 'We protect people, assets, and the integrity of every installation.' }, { title: 'Clarity in delivery', text: 'We communicate early, document carefully, and keep decisions visible.' }, { title: 'Craft with accountability', text: 'We take ownership from first survey through final handover.' }, { title: 'Progress with purpose', text: 'We use technology where it improves resilience, efficiency, or value.' }]
export const coreValues = ['Integrity in every commitment', 'Respect for people and expertise', 'Continuous learning and improvement', 'Practical innovation that delivers value']
